Naming/AsciiIdentifiers:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
