apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: g
  namespace: the-g-team
  labels:
    team: the-g-team
spec:
  image: {{ image }}
  port: 9292
  ingresses:
    - https://g.nav.no
  prometheus:
    enabled: true
  env:
    - name: RACK_ENV
      value: production
  observability:
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 400Mi
    requests:
      cpu: 50m
      memory: 150Mi
  liveness:
    path: /api/v1/grunnbeloep
  readiness:
    path: /api/v1/grunnbeloep
