apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: g
  namespace: aura
  labels:
    team: aura
spec:
  image: ghcr.io/navikt/g:{{ TAG }}
  port: 9292
  ingresses:
    - https://g.nav.no
  prometheus:
    enabled: true
  env:
    - name: RACK_ENV
      value: production
  resources:
    limits:
      cpu: 300m
      memory: 400Mi
    requests:
      cpu: 50m
      memory: 200Mi
